version: '3.8'
services:
    php-apache-environment:
        container_name: appache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - database
        volumes:
            - .:/var/www/html/
        ports:
            - 5000:80
    database:
        container_name: database
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: projet_poo
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        ports:
            - "9907:3306"